name: Build Docker Image

on:
  push:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Build Docker image
        run: docker build -t myapp .
      - name: Run container and test
        run: |
          docker run -d -p 5000:5000 --name test-container myapp
          sleep 5
          curl http://localhost:5000
          docker stop test-container